### ISSUE TITLE
Android ceash  TypeError: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by mazhiyuam** [ji-ba-app/ji-ba-cdn#1]
Android 13
Xiaomi 12S
MIUI14

```
========================================
2024-04-28 08:23:15 data_app_crash (text, 2828 bytes)
Process: com.jiba.shanji
PID: 13776
UID: 10659
Frozen: false
Flags: 0x38883e44
Package: com.jiba.shanji v1 (1.0)
Foreground: Yes
Process-Runtime: 900813182
Build: Xiaomi/mayfly/mayfly:13/TKQ1.220829.002/V14.0.3.0.TLTCNXM:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

com.facebook.react.common.JavascriptException: TypeError: Cannot convert undefined value to object

This error is located at:
    in HardwareInfo
    in StaticContainer
    in EnsureSingleNavigator
    in SceneView
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in CardSheet
    in RCTView
    in Unknown
    in Unknown
    in PanGestureHandler
    in PanGestureHandler
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Card
    in CardContainer
    in RNSScreen
    in Unknown
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in InnerScreen
    in Screen
    in MaybeScreen
    in RNSScreenContainer
    in ScreenContainer
    in MaybeScreenContainer
    in RCTView
    in Unknown
    in Background
    in CardStack
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaProviderCompat
    in RNGestureHandlerRootView
    in GestureHandlerRootView
    in StackView
    in PreventRemoveProvider
    in NavigationContent
    in Unknown
    in StackNavigator
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner
    in App
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes, stack:
HardwareInfo@1:1562985
renderWithHooks@1:363188
beginWork$1@1:404948
performUnitOfWork@1:391354
workLoopSync@1:391215
renderRootSync@1:391099
performSyncWorkOnRoot@1:388516
flushSyncCallbacks@1:352830
batchedUpdatesImpl@1:405342
batchedUpdates@1:345613
_receiveRootNodeIDEvent@1:345886
receiveEvent@1:399773
__callFunction@1:108780
anonymous@1:107132
__guard@1:108085
callFunctionReturnFlushedQueue@1:107090

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ZLY201** [comment]
Solved In v1.0.0. Thanks for your report! <3
